services:
  - type: web
    name: RAG
    env: python3.9
    buildCommand: |
      # Download ChromeDriver
      CHROME_DRIVER_VERSION=$(curl -sS https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/win64/chromedriver-win64.zip)
      wget -N https://chromedriver.storage.googleapis.com/134.0.6998.165/chromedriver_linux64.zip -P ~/tmp
      unzip ~/tmp/chromedriver_linux64.zip -d ~/tmp
      sudo mv -f ~/tmp/chromedriver /usr/local/bin/chromedriver
      sudo chown root:root /usr/local/bin/chromedriver
      sudo chmod 0755 /usr/local/bin/chromedriver

    envVars:
      - key: CHROMEDRIVER_PATH
        value: /usr/local/bin/chromedriver