services:
  - type: web
    name: RAG
    runtime: python3
    envVars:
      - key: GEMINI_API_KEY
        value: "AIzaSyDWiXZueejp1eE61y5FeQf-S4U2EM3U0rQ"
    buildCommand: |
      apt-get update && apt-get install -y wget unzip
      pip install -r requirements.txt
      # Install Google Chrome
      wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt install -y ./google-chrome-stable_current_amd64.deb
      # Install ChromeDriver (using version 134.0.6998.165 for Linux)
      wget -q https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/linux64/chromedriver-linux64.zip
      unzip chromedriver-linux64.zip -d /usr/local/bin/
      chmod +x /usr/local/bin/chromedriver
      rm chromedriver-linux64.zip
    startCommand: uvicorn hack:app --host 0.0.0.0 --port 8000
    plan: free
